### ISSUE TITLE
湘雅新校区预约报错 code1

### ISSUE THREAD

**Issue by fdwhy-csu** [founder-yu/CSU-Library#1]
您好！！
您的脚本非常好用，我有个问题，就是seat数组应当是只包含了新校区的座位，如果需要在其他校区预约需要填写什么座位呢？很奇怪，湘雅新校区的图书馆座位只有ID号，系统内预定也是4位数字，没有其他校区的字母代号。能请教您一下吗？我直接填写数字最后得到结果是code1

**Comment by founder-yu** [comment]
你好，目前脚本仅支持新校区，也就是seat数组目前仅可填写新校区桌号，如需预约其他校区，需扩展seat.csv文件，本人将在一周内（2022年11月7日）完成湘雅扩展（目前正在开发桌面应用，时间较少），待维护完成后，只需在seat数组中填写形如“医学院二楼2000”之类的桌号即可。本人也有打算进一步优化此项目，如移动端循环抢座直至成功，如有意愿协助开发，请留一个邮箱或联系方式，谢谢！

**Comment by founder-yu** [comment]
已完成数据扩展并简化部分代码，目前代码已在新校区测试，无误。

**Comment by fdwhy-csu** [comment]
非常感谢您的付出！近期湘雅在期末和期中考试，没有及时回复您非常抱歉。今天测试了新的代码，traceback报在line68，我测试了一下考虑是湘雅新校区NO的dtype是int，所以会索引超出数组范围，显示溢出。我尝试seat_data["NO"] = seat_data["NO"].astype(object)，但是发现没有什么作用,可以请您看看吗？可以联系我saltyfish_csu@foxmail.com 代码能力比较弱，但是可以做些简单的测试
